### ISSUE TITLE
You dont really clear the candidates but reset the count instead. Is it really your purpose here?

### ISSUE THREAD

**Issue by code2moon** [ccoincash/spirit_stone#1]
https://github.com/spirit-stone-world/token-core/blob/de3f8b0eabedd9fdcbd9bc70f358f25af140445b/src/spirit_stone.cairo#L356C9-L356C26

**Comment by ccoincash** [comment]
Yeah, it works as expected to avoid clearing LegacyMap which is expensive

**Comment by code2moon** [comment]
Why don't you verify your code with your deployed contract there?

**Comment by ccoincash** [comment]
the Starkscan did not support to verify it when I uploaded this contract.
